# Generated by Django 4.2 on 2024-12-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_discount_alter_lesson_related_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='course_headline',
        ),
    ]
