# Generated by Django 4.2 on 2024-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
